// tools/cards.mjs - GENERATED by project-discipline. Do NOT edit this file.
// Regenerate:  node "<skill>\scripts\cards-init.mjs" --root "<this project>"
// Your conventions live in tools/cards.config.mjs.
//
// Why this file is generated: the rules are one implementation (the skill), and
// so is the way a project invokes them. Hand-copying that invocation into every
// project is how the copies drifted apart with nothing to catch it.
import { existsSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const STAMP = '35cbd315e719'
const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')

// A checkout has the config file; a published tarball does not (tools\ is not in
// the package's files list). Skipping there - loudly - keeps a consumer's
// npm test working while still saying out loud that nothing was checked.
//
// "docs.config.mjs" is the PRE-RENAME name (before 2026-09-22, when this whole tool was
// called "docs*"). A project that has not been regenerated yet keeps working through this
// fallback - and says so, so the next reader knows to re-run the generator.
const legacyConfigPath = join(here, 'docs.config.mjs')
const configPath = existsSync(join(here, 'cards.config.mjs'))
  ? join(here, 'cards.config.mjs')
  : legacyConfigPath
if (!existsSync(configPath)) {
  console.log('cards: skipped - tools/cards.config.mjs is missing (not a checkout?); nothing was checked')
  process.exit(0)
}
if (configPath === legacyConfigPath) {
  console.log('cards: note - this project still uses the old name tools/docs.config.mjs;'
    + ' re-run the generator to rename it: node "<skill>\scripts\cards-init.mjs" --root "."')
}

// Locate the skill. HANDOFF_CARDS_CHECK (or the older HANDOFF_DOCS_CHECK) may name the
// skill's scripts directory or any file inside it.
const fromEnv = process.env.HANDOFF_CARDS_CHECK || process.env.HANDOFF_DOCS_CHECK
const checker = [
  fromEnv ? join(fromEnv.endsWith('.mjs') ? dirname(fromEnv) : fromEnv, 'cli.mjs') : null,
  join(homedir(), '.dsh', 'skills', 'project-discipline', 'scripts', 'cli.mjs'),
].filter(Boolean).find((p) => existsSync(p))
if (!checker) {
  console.error('cards: the project-discipline skill was not found.')
  console.error('  install it (junction into ~/.dsh/skills/project-discipline), or set')
  console.error('  HANDOFF_CARDS_CHECK=<path to the skill scripts directory>')
  process.exit(2)
}

const mod = await import(pathToFileURL(configPath).href)
const { config } = mod
const { runCli, runBreaktest } = await import(pathToFileURL(checker).href)
const argv = process.argv.slice(2)

// One entry point, two modes. The breaktest needs the same bootstrap, so giving it a second
// file only created a copy that could drift from this one - measured 2026-09-20: the two files
// were byte-identical except for their last line.
//
// The cases may sit next to the config object or nested inside it. This line used to read ONLY
// the nested one while the generated template exports the other, so every project's calibration
// ran with zero cases and still printed four green rows. Reading both is the fix; runBreaktest
// now also states how many cases it was handed, so zero can never look like success again.
if (argv[0] === 'breaktest') {
  process.exit(runBreaktest({ ...config, root, ...((config && config.breaktest) || mod.breaktest || {}) }))
}
process.exit(runCli({ root, ...config }, argv, { stamp: STAMP, self: 'tools/cards.mjs' }))
